compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  ### Advisories:

  # Issue: Regular Expression Denial of Service (ReDOS)
  # URL: https://github.com/advisories/GHSA-257v-vj4p-3w2h
  # color-string is listed as a dependency of 'color' which is brought in by
  # @metamask/jazzicon v2.0.0 but there is work done on that repository to
  # remove the color dependency. We should upgrade
  - 1089718

  # Issue: Issue: Babel has inefficient RexExp complexity in generated code with .replace when transpiling named capturing groups
  # We are ignoring this on April 24, 2025 to unblock CI, we will follow with a proper fix or confirmation this does not affect our users
  - 1104001

  # Issue: minimatch has a ReDoS via repeated wildcards with non-matching literal in pattern
  # Only affects dev/build-time dependencies (eslint-plugin-n, glob) — not shipped to users.
  # URL: https://github.com/advisories/GHSA-3ppc-4f35-3m26
  - 1113459

  ### Package Deprecations:

  # React-tippy brings in popper.js and react-tippy has not been updated in
  # three years.
  - 'popper.js (deprecation)'

  # Material UI dependencies are planned for removal
  - '@material-ui/core (deprecation)'
  - '@material-ui/styles (deprecation)'
  - '@material-ui/pickers (deprecation)'

  # Dependencies brought in by @truffle/decoder that are deprecated:
  - 'cids (deprecation)' # via @ensdomains/content-hash
  - 'multibase (deprecation)' # via cids
  - 'multicodec (deprecation)' # via cids

  # gridplus-sdk brings this deprecated stub types package.
  - '@types/uuid (deprecation)'

  # Currently in use for the network list drag and drop functionality.
  # Maintenance has stopped and the project will be archived in 2025.
  - 'react-beautiful-dnd (deprecation)'
  # New package name format for new versions: @ethereumjs/wallet.
  - 'ethereumjs-wallet (deprecation)'

  # Deprecated package still used by older versions of our packages, to be eliminated soon as we
  # update.
  - '@metamask/error-reporting-service (deprecation)'

  # Deprecated transitive dependency of better-sqlite3. No maintained alternative available yet.
  - 'prebuild-install (deprecation)'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: 'https://raw.githubusercontent.com/LavaMoat/LavaMoat/main/packages/yarn-plugin-allow-scripts/bundles/@yarnpkg/plugin-allow-scripts.js'
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'
  - path: .yarn/plugins/@yarnpkg/plugin-preview-builds.cjs

# Configure the NPM minimal age gate to 3 days, meaning packages must be at
# least 3 days old to be installed.
npmMinimalAgeGate: 4320 # 3 days (in minutes)

# Override the minimal age gate, allowing certain packages to be installed
# regardless of their publish age.
npmPreapprovedPackages:
  - '@metamask/*'
  - '@metamask-previews/*'
  - '@lavamoat/*'
  - 'lavamoat-core'
  - 'lavamoat-browserify'
  - 'lavamoat-tofu'
  - 'lavamoat-node'
  - 'lavamoat'
  - 'extension-port-stream'
